### ISSUE TITLE
Inputs Actions and Input Mapping Contexts cannot be imported or used 

### ISSUE THREAD

**Issue by looptrader** [XpycT/EnhancedCamera#1]
When creating a project using EnhancedCamera the provided actions and mapping context cannot be used or selected anywhere. Also tried importing or copy pasting them without success.
Ended up rebuilding them with a bit of trial and error. 

Thanks for the great tool !

**Comment by XpycT** [comment]
To select assets from the plugin, you need to select "show plugin content" in the cogwheel

![зображення](https://github.com/XpycT/EnhancedCamera/assets/120016/907ac320-fe0d-477c-927d-0060d10f5bfb)

**Comment by azpublic** [comment]
Hey! Thanks for the reply. I don't think that's it though. If you download the Release you will notice that the Files inside the3 Content folder of the plugin are all 130b in size. When you open these files  with a text editor you will find something like : 

version https://git-lfs.github.com/spec/v1
oid sha256:f3887c3aaaf9b53df6d28904e7ef4d8ea990754d1fe77666bba3b46a6f02094b
size 1459

Which is a pointer to a file on git Large file system. I had to manually download each file from github and replace them.

Anyway the plugin works great so thanks.
